version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sbdocker
    networks:
      spring-boot-docker-network:

  app:
    container_name: springboot-mysql-container
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      spring-boot-docker-network:
    restart: on-failure

networks:
  spring-boot-docker-network: